"""baseline

Revision ID: ace7d9ed269a
Revises: 
Create Date: 2026-10-10 18:01:15.077195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace7d9ed269a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('cleaned_answer', sa.TEXT(), nullable=False),
    sa.Column('expected_answer', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question', 'cleaned_answer', name='_question_cleaned_uc')
    )
    with op.batch_alter_table('accepted_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accepted_answers_id'), ['id'], unique=False)

    op.create_table('flagged_mismatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('expected_answer', sa.TEXT(), nullable=False),
    sa.Column('direction', sa.TEXT(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('flagged_count', sa.Integer(), nullable=True),
    sa.Column('first_flagged_at', sa.DateTime(), nullable=True),
    sa.Column('last_flagged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question', 'expected_answer', name='_question_expected_uc')
    )
    with op.batch_alter_table('flagged_mismatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_mismatches_id'), ['id'], unique=False)

    op.create_table('question_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.TEXT(), nullable=False),
    sa.Column('key_value', sa.TEXT(), nullable=False),
    sa.Column('tip', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_type', 'key_value', name='_tip_keytype_keyvalue_uc')
    )
    with op.batch_alter_table('question_tips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_tips_id'), ['id'], unique=False)

    op.create_table('seen_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.TEXT(), nullable=False),
    sa.Column('times_shown', sa.Integer(), nullable=True),
    sa.Column('last_shown', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='_user_question_uc')
    )
    with op.batch_alter_table('seen_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seen_questions_id'), ['id'], unique=False)

    op.create_table('sound_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sound', sa.TEXT(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('successes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sound', name='_user_sound_uc')
    )
    with op.batch_alter_table('sound_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sound_progress_id'), ['id'], unique=False)

    op.create_table('strength_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facet', sa.TEXT(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('last_practice', sa.DateTime(), nullable=True),
    sa.Column('miss_count', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', 'user_id', 'facet', name='_tag_user_facet_uc')
    )
    with op.batch_alter_table('strength_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strength_table_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=True),
    sa.Column('current_unit', sa.Integer(), nullable=True),
    sa.Column('graduated_units', sa.TEXT(), nullable=True),
    sa.Column('hsk_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clerk_user_id'), ['clerk_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_guest_id'), ['guest_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('word_tier_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag', name='_user_tag_tier_uc')
    )
    with op.batch_alter_table('word_tier_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_tier_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_tier_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_tier_progress_id'))

    op.drop_table('word_tier_progress')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_guest_id'))
        batch_op.drop_index(batch_op.f('ix_users_clerk_user_id'))

    op.drop_table('users')
    with op.batch_alter_table('strength_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strength_table_id'))

    op.drop_table('strength_table')
    with op.batch_alter_table('sound_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sound_progress_id'))

    op.drop_table('sound_progress')
    with op.batch_alter_table('seen_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seen_questions_id'))

    op.drop_table('seen_questions')
    with op.batch_alter_table('question_tips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_tips_id'))

    op.drop_table('question_tips')
    with op.batch_alter_table('flagged_mismatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_mismatches_id'))

    op.drop_table('flagged_mismatches')
    with op.batch_alter_table('accepted_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accepted_answers_id'))

    op.drop_table('accepted_answers')
    # ### end Alembic commands ###
